name: trading-bot
services:
  app:
    build:
      context: .
      dockerfile: etc/go/Dockerfile
    container_name: trading-bot
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./be/.env
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./be:/app
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "api.binance.com:13.225.103.45"
      - "api1.binance.com:13.225.103.45"
      - "api2.binance.com:13.225.103.45"
      - "api3.binance.com:13.225.103.45"
    networks:
      - trading-bot-network
      - mysql-network
      - redis-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8000/health",
        ]
      interval: 180s
      timeout: 3s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  trading-bot-network:
    driver: bridge
    name: trading-bot-network
  mysql-network:
    driver: bridge
    name: mysql-network
    external: true
  redis-network:
    driver: bridge
    name: redis-network
    external: true
