package models

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

// Signal represents a trading signal generated by the system
type Signal struct {
	ID       uint   `gorm:"primaryKey;column:id" json:"id"`
	Symbol   string `gorm:"column:symbol;size:20;not null;index" json:"symbol"`
	StrategyID uint `gorm:"column:strategy_id;not null;index" json:"strategy_id"`

	// Signal Info
	SignalCategory string  `gorm:"column:signal_category;size:20;not null;index" json:"signal_category"` // BUY/SELL/STRONG_BUY/STRONG_SELL/WAIT
	SignalValid    bool    `gorm:"column:signal_valid;default:false;index" json:"signal_valid"`
	TotalScore     float64 `gorm:"column:total_score;type:DECIMAL(10,3);not null" json:"total_score"`
	Confidence     float64 `gorm:"column:confidence;type:DECIMAL(10,3);not null" json:"confidence"`

	// Price Info
	CurrentPrice     float64 `gorm:"column:current_price;type:decimal(20,8);not null" json:"current_price"`
	PrimaryTimeframe string  `gorm:"column:primary_timeframe;size:10;not null" json:"primary_timeframe"`

	// Trading Plan (Garis-garis visual)
	TPPrice       float64 `gorm:"column:tp_price;type:decimal(20,8)" json:"tp_price"`
	SLPrice       float64 `gorm:"column:sl_price;type:decimal(20,8)" json:"sl_price"`
	SupportPrice  float64 `gorm:"column:support_price;type:decimal(20,8)" json:"support_price"`
	ResistancePrice float64 `gorm:"column:resistance_price;type:decimal(20,8)" json:"resistance_price"`
	RiskRewardRatio float64 `gorm:"column:risk_reward_ratio;type:decimal(10,2)" json:"risk_reward_ratio"`

	// Entry Info
	AvgEntryPrice float64 `gorm:"column:avg_entry_price;type:decimal(20,8)" json:"avg_entry_price"`
	EntryMode     string  `gorm:"column:entry_mode;type:ENUM('CONSERVATIVE','AGGRESSIVE');default:'CONSERVATIVE'" json:"entry_mode"`

	// Capital & Position
	TradingCapital      float64 `gorm:"column:trading_capital;type:decimal(20,2)" json:"trading_capital"`
	TotalPositionValue  float64 `gorm:"column:total_position_value;type:decimal(20,2)" json:"total_position_value"`
	TotalPositionQty    float64 `gorm:"column:total_position_qty;type:decimal(20,8)" json:"total_position_qty"`
	MaxRiskUSDT         float64 `gorm:"column:max_risk_usdt;type:decimal(20,2)" json:"max_risk_usdt"`
	MaxRiskPercent      float64 `gorm:"column:max_risk_percent;type:decimal(10,2)" json:"max_risk_percent"`
	TargetProfitUSDT    float64 `gorm:"column:target_profit_usdt;type:decimal(20,2)" json:"target_profit_usdt"`
	TargetProfitPercent float64 `gorm:"column:target_profit_percent;type:decimal(10,2)" json:"target_profit_percent"`
	EffectiveLeverage   float64 `gorm:"column:effective_leverage;type:decimal(10,2)" json:"effective_leverage"`

	// Config
	Leverage     int     `gorm:"column:leverage;default:1" json:"leverage"`
	BufferPercent float64 `gorm:"column:buffer_percent;type:decimal(10,3)" json:"buffer_percent"`

	// SNAPSHOTS (JSON)
	StrategySnapshot  JSONMap    `gorm:"column:strategy_snapshot;type:json;not null" json:"strategy_snapshot"`
	OHLCSnapshot      JSONMap    `gorm:"column:ohlc_snapshot;type:json;not null" json:"ohlc_snapshot"`
	IndicatorValues   JSONArray  `gorm:"column:indicator_values;type:json;not null" json:"indicator_values"`
	EntryLevels       JSONArray  `gorm:"column:entry_levels;type:json;not null" json:"entry_levels"`

	// Metadata
	CreatedAt time.Time  `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt time.Time  `gorm:"autoUpdateTime" json:"updated_at"`
}

func (Signal) TableName() string {
	return "signals"
}

// JSONArray for JSON array fields
type JSONArray []interface{}

func (a JSONArray) Value() (driver.Value, error) {
	if a == nil {
		return nil, nil
	}
	return json.Marshal(a)
}

func (a *JSONArray) Scan(value interface{}) error {
	if value == nil {
		*a = nil
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("failed to unmarshal JSON array: %v", value)
	}
	return json.Unmarshal(bytes, a)
}
